### ISSUE TITLE
Support for pyformat

### ISSUE THREAD

**Issue by AresEkb** [vertica/vertica-python#384] opened 2020-07-08 12:41 UTC
Hi

It seems that `vertica-python` doesn't support pyformat for parameter formatting. I added the following hack into vertica_python/vertica/cursor.py:
```
operation = operation % {k: self.object_to_string(v, is_copy_data) for k, v in parameters.items()}
```
Here is the commit into my fork: https://github.com/AresEkb/vertica-python/commit/1c288df806fb1a7ed3985ac8b810d57eef9f9aa1

I'm not sure it's a right approach. Could you please fix it the right way in your repository?

**Comment by sitingren** [comment] 2020-07-08 14:34
Duplicate of #385

**Closed by sitingren** 2020-07-08 14:34 UTC

**Comment by AresEkb** [comment] 2020-07-08 16:44
It's not a duplicate, it's an absolutely different issue.

It seems that `vertica-python` supports only named params of the following form `:param1`. And it doesn't support params of the form `%(param)s`. Please see https://www.python.org/dev/peps/pep-0249/#paramstyle

**Comment by sitingren** [comment] 2020-07-09 09:48
PEP 249 lists possible paramstyle values, that doesn't mean a client has to implement all those options. AFAIK, we don't have plan to support more paramstyles, as it would add maintenance burdens (eg. testing, compatibility) in the future. And I think a direct way to get rid of this problem is replacing parameter markers `%(param)s` in the query string with desired `:param` markers.
