### ISSUE TITLE
Read Timeout is Ignored With Lower Connection Timeout

### ISSUE THREAD

**Issue by waterlooDebate** [vertica/vertica-python#183] opened 2017-11-07 17:26 UTC
```
vertica_config = {
        'host': some_host,
        'user': some_user,
        'password': some_password,
        'database': some_db,
        'read_timeout': 600,
        'connection_timeout': 10
    }
```

After 10s attempting to read from Vertica, the following is thrown (six.raise_from was monkey patched to see what the underlying exception was since Python 2.7 doesn't like exception chaining).
The read_timeout is set to 600s so you would expect this not to timeout after 10s.

```
Traceback (most recent call last):
  File "/workspace/scripts/python/vertica-diff.py", line 274, in <module>
    main()
  File "/workspace/scripts/python/vertica-diff.py", line 212, in main
    options.hours_subtract)
  File "/workspace/scripts/python/vertica-diff.py", line 73, in get_vertica_data
    cursor.execute(vertica_query)
  File "/workspace/scripts/python/.venv/lib/python2.7/site-packages/vertica_python/vertica/cursor.py", line 113, in execute
    self._message = self.connection.read_message()
  File "/workspace/scripts/python/vertica-diff.py", line 42, in monkey_patch_read_connection
    raise e
socket.timeout: timed out
```

**Comment by sitingren** [comment] 2018-08-27 20:58
Which version of vertica_python package do you use? I guess this is a duplicate of issue #198.

**Comment by sitingren** [comment] 2019-04-11 20:45
Duplicate of #198

**Closed by sitingren** 2019-04-11 20:45 UTC
